/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Funcion;
import modelo.Respuesta;
import modelo.Restriccion;
import modelo.Series;

/**
 *
 * @author Daniel
 */
public class VistaGrafica extends javax.swing.JFrame {

    /**
     * Creates new form VistaGrafica
     */
    int nRestricciones;
    double x1, x2, y1, y2;
    ArrayList<Restriccion> restricciones;
    ArrayList<Respuesta> respuestas;
    Series serie;
    Funcion funcion;

    public VistaGrafica() {
        initComponents();
        serie = new Series();
        restricciones = new ArrayList<>();
        respuestas = new ArrayList<>();
        nRestricciones = 0;
        jButtonRegistro.setEnabled(false);
        jButtonNRestricciones.setEnabled(false);
    }

    private void hablilitarforms(boolean bandera) {
        jTextFieldX.setEditable(bandera);
        jTextFieldY.setEditable(bandera);
        jTextFieldC.setEditable(bandera);
    }

    private void limpiarpuntos() {
        jTextFieldX.setText("");
        jTextFieldY.setText("");;
        jTextFieldC.setText("");
    }

    private Respuesta CalcularRepuesta(Restriccion r1, Restriccion r2) {
        double det = (r1.x * r2.y) - (r1.y * r2.x);
        if (det != 0.0) {
            double x = (r2.y * r1.d - r1.y * r2.d) / det;
            double y = (r1.x * r2.d - r2.x * r1.d) / det;
            return new Respuesta(x, y, 'U');
        } else {
            double aux = r2.x / r1.x;
            if (aux * r1.d == r2.d) {
                return new Respuesta(0, 0, 'I');
            } else {
                return new Respuesta(0, 0, 'N');
            }
        }

    }

    private void encontrrapuntos(List<Restriccion> restricciones, ArrayList<Respuesta> respuestas) {
        for (Restriccion r1 : restricciones) {
            for (Restriccion r : restricciones) {
                respuestas.add(this.CalcularRepuesta(r1, r));
            }
        }
       
    }

    private void calcularpuntos(double x, double y, double c,boolean bandera) {

        restricciones.add(new Restriccion(nRestricciones, x, y, c,bandera));
        if (x == 0) {
            y1 = y2 = c;
        } else if (y == 0) {
            x1 = x2 = c;
        } else {

            x1 = c / x;
            y1 = 0.0;
            x2 = 0;
            y2 = c / y;
            System.out.println(x1 + " " + y2);
            serie.addSerie(x1, y1, x2, y2, jLabelNRestriccion.getText());
        }
    }

    private void cumple(List<Restriccion> restricciones, ArrayList<Respuesta> respuestas) {
       for(Respuesta res:respuestas) {
            for (Restriccion restric : restricciones) {
                
                if(!evaluar(restric,res)){
                    System.out.println("entro");
                res.setCumple(false);}
            }
        }
    }
public boolean evaluar(Restriccion restriccion,Respuesta respuesta)
{
    double z=restriccion.getX()*respuesta.getX()+restriccion.getY()*respuesta.getZ();
     System.out.println(restriccion.getD());
     System.out.println(z<=restriccion.getD());
     boolean bandera;
    if(!restriccion.tipo)
    {System.out.println("menor igual");
        return z<=restriccion.getD();
        
    }
    else
    {return z>=restriccion.getD();}
   
}
    private void calcularz(ArrayList<Respuesta> respuestas) {
        System.out.println(funcion.getX() + " " + funcion.getY());
        for (Respuesta r : respuestas) {
            if (r.getX() < 0 || r.getY() < 0) {
                r.setZ(0);
            } else {
                r.setZ(funcion.getX() * r.getX() + funcion.getY() * r.getY());
                // System.out.println(funcion.getX()*r.getX()+funcion.getY()*r.getY()); 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNRestricciones = new javax.swing.JButton();
        jTextFieldNRestricciones = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldC = new javax.swing.JTextField();
        jTextFieldY = new javax.swing.JTextField();
        jTextFieldX = new javax.swing.JTextField();
        jButtonRegistro = new javax.swing.JButton();
        jLabelNRestriccion = new javax.swing.JLabel();
        jComboBoxRadio = new javax.swing.JComboBox();
        jButtonObjetivo = new javax.swing.JButton();
        jComboBoxFuncion = new javax.swing.JComboBox();
        jLabelIgual = new javax.swing.JLabel();
        jTextFieldXF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFY = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonNRestricciones.setText("Numero De Restricciones");
        jButtonNRestricciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNRestriccionesActionPerformed(evt);
            }
        });

        jLabel1.setText("X");

        jLabel2.setText("Y");

        jTextFieldC.setEditable(false);

        jTextFieldY.setEditable(false);

        jTextFieldX.setEditable(false);

        jButtonRegistro.setText("Registrar");
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });

        jLabelNRestriccion.setText("   ");

        jComboBoxRadio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<=", ">=" }));

        jButtonObjetivo.setText("Funcion Objetivo");
        jButtonObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObjetivoActionPerformed(evt);
            }
        });

        jComboBoxFuncion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MinZ", "MaxZ" }));

        jLabelIgual.setText("=");

        jLabel3.setText("+");

        jLabel4.setText("X");

        jLabel5.setText("Y");

        jLabel6.setText("+");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonNRestricciones)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonRegistro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabelNRestriccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(8, 8, 8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldNRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBoxRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonObjetivo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldXF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonObjetivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIgual)
                    .addComponent(jTextFieldXF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldFY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNRestricciones)
                    .addComponent(jTextFieldNRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistro)
                    .addComponent(jLabelNRestriccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNRestriccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNRestriccionesActionPerformed
        // TODO add your handling code here:
        this.jTextFieldNRestricciones.setEditable(false);
        jButtonNRestricciones.setEnabled(false);
        hablilitarforms(true);
        jButtonRegistro.setEnabled(true);
        jLabelNRestriccion.setText("Restriccion #" + (++nRestricciones));
    }//GEN-LAST:event_jButtonNRestriccionesActionPerformed


    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
        // TODO add your handling code here:

        try {boolean bandera=false;
            if(jComboBoxRadio.getSelectedIndex()==0)
            {bandera=true;}
           
            calcularpuntos(Double.parseDouble(jTextFieldX.getText()), Double.parseDouble(jTextFieldY.getText()), Double.parseDouble(jTextFieldC.getText())
            ,bandera);
            jLabelNRestriccion.setText("Restriccion #" + (++nRestricciones));
            limpiarpuntos();
            if (Integer.parseInt(jTextFieldNRestricciones.getText()) + 1 == nRestricciones) {
                encontrrapuntos(restricciones, respuestas);
               
                cumple(restricciones, respuestas);
                int i=0;
                for (Respuesta r : respuestas) {
                    if(r.isCumple())
                    {i++;}
                }
                System.out.println("las respuestas son "+i);
                
                calcularz(respuestas);
                for (Respuesta r : respuestas) {
                    System.out.println(r.getX() + "," + r.getY() + "," + r.getZ());
                }
                jButtonRegistro.setEnabled(false);

            }
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(rootPane, "Error en registro de campos intetenlo otravez");
        }


    }//GEN-LAST:event_jButtonRegistroActionPerformed

    private void jButtonObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObjetivoActionPerformed
        // TODO add your handling code here:
        try {
            if (Double.parseDouble(jTextFieldXF.getText()) <= 0 || Double.parseDouble(jTextFieldFY.getText()) <= 0) {
                throw new java.lang.NumberFormatException();
            }
            char tipo = 'M';
            if (jComboBoxFuncion.getSelectedIndex() == 0) {
                tipo = 'm';
            }
            funcion = new Funcion(Double.parseDouble(jTextFieldXF.getText()), Double.parseDouble(jTextFieldFY.getText()), tipo);
            System.out.println(funcion.getX() + "," + funcion.getY());
            jButtonNRestricciones.setEnabled(true);
            jButtonObjetivo.setEnabled(false);
            jTextFieldXF.setEditable(false);
            jTextFieldFY.setEditable(false);
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(rootPane, "Error en el ingreso de datos intente de nuevo");
        }
    }//GEN-LAST:event_jButtonObjetivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNRestricciones;
    private javax.swing.JButton jButtonObjetivo;
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JComboBox jComboBoxFuncion;
    private javax.swing.JComboBox jComboBoxRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelIgual;
    private javax.swing.JLabel jLabelNRestriccion;
    private javax.swing.JTextField jTextFieldC;
    private javax.swing.JTextField jTextFieldFY;
    private javax.swing.JTextField jTextFieldNRestricciones;
    private javax.swing.JTextField jTextFieldX;
    private javax.swing.JTextField jTextFieldXF;
    private javax.swing.JTextField jTextFieldY;
    // End of variables declaration//GEN-END:variables
}
